### PR TITLE
Made Robinhood.py Python 2 compliant

### PR DESCRIPTION
**Pull request by jsmwoolf**
The Robinhood.py file has been fixed to be Python 2 compliant.

However, converting Python 3 with the instructions won't entirely work since, for some reason, the 2to3 won't pick up urllib.getproxies() to urllib.request.getproxies().  That change has to be done manually.

### CODE REVIEW

**Comment by Jamonek** [comment]
I think it would be better if we maintained 2 branches for each version of Python.

**Comment by jsmwoolf** [comment]
Will the branches be maintained within the same repository?

**Comment by Jamonek** [comment]
Yes

**Comment by jsmwoolf** [comment]
Do you have a branch I can merge the Python 3 version of the code to?  I just created a branch to separate Python 3 from Python 2.

**Pull request merged**
