### PR TITLE
Remove password and support two factor auth

### PR DESCRIPTION
**Pull request by noamlerner**
This should not be storing the users password anywhere past its use. 

I also added functionality to support two factor authentication instead of throwing an error.

### CODE REVIEW

**Comment by aamazie** [comment]
If @Jamonek would ever approve my PR, I've added functionality that uses this storage. The functionality re-logs in if the order function fails. Added try/excepts to the parent order methods. Robinhood asks for an additional log in now for the first buy and sell of the day.

I just use security around the machine I run my code on instead of getting rid of the password storage.

**Comment by aamazie** [comment]
The MFA bit looks good, though. I'll add that to my repo even if @Jamonek won't. Thank you, @noamlerner

**Comment by aamazie** [comment]
Actually, nevermind about the MFA.. It seems like it could just be passed as a third parameter and that error was thrown if there is still a requirement after its handled above. Plus, returning something there would negate the if statement below.

**Comment by aamazie** [comment]
To clarify, it is currently being passed as an optional third parameter.

**Comment by noamlerner** [comment]
@aamazie 

Even if you are trying to relog, you could pass the password in. Storing is insecure. 

It wouldn't really negate the flow below the if statement. Here's how it works:
Say you use login prompt (as you always should, instead of storing your password in your code), you need to supply your user/pass before you even have access to MFA, so that third parameter to this function actually pointless as it currently stands since there's no way of providing it. 

Once you get the mfa_required message, you also know that the second factor auth text has been sent, so now it can be inputted. Once you supply the mfa, the method calls itself again supplying the mfa code. Since it's there now, "mfa_required" won't be an issue and it will move on to the next if statement.

**Comment by aamazie** [comment]
Some users, including myself, wouldn't want to always use the login prompt. My code runs automatically and restarts automatically, so it needs to have a stored password. Maybe write a different login prompt function for this?

**Comment by Jamonek** [comment]
Hey @aamazie, I’ll review your PR now. Sorry I’ve been out on vacation

**Comment by aamazie** [comment]
No problem. Hope you enjoyed.

**Comment by mayurpise** [comment]
checked-out latest code from repo but although script asks for MFA code but it still fails to login, anyone such issue

**Comment by aamazie** [comment]
@mayurpise My repo has fixes for that.

**Comment by mayurpise** [comment]
Thank you let me try that

**Pull request merged**
