### PR TITLE
Separate order types

### PR DESCRIPTION
**Pull request by ciresnave**
Wrote a replacement for all order placing methods in parallel with the existing ones.
New methods have a single method to place each order type.
There is also a submit_order() method which contains some argument checks and actually handles the submission of the order to Robinhood.
I also added myself to the CONTRIBUTORS file since this is a substantial addition.

### CODE REVIEW

**Comment by ciresnave** [comment]
I fully expect some criticism on my code.  In my defense, I'm a long time C/C++ programmer who is relatively new to Python so I write like a C programmer.  I tried to keep my code styled like the rest of Robinhood.py but I may have missed something or possibly not used best practices. Let me know what you all think.

**Comment by bdowling** [comment]
I'm not certain why this was merged, there was no feedback or comments that help clarify why this is needed.  All of these convenience functions really pollute the API and should not be part of the core functionality.

**Comment by ciresnave** [comment]
I was hoping to get feedback before anyone merged it. However, the original API did not support all order types (at least not without standing on your head) and this new system does. I believe the old ordering code should probably be removed as the new submit_order() from this provides the same functionality more directly matching RobinHood's actual interface. The calls for individual order types should be moved into a secondary helpers API like some of us have begun to discuss in comments elsewhere.

**Comment by bdowling** [comment]
@ciresnave  I feel I may have done a dis-service in not working to get #44 to a state that it could be merged sooner (life happens!), as we were both addressing the problems with place_order and other things.

I did a quick comparison of your submit_order compared to the updated place_order I have in #44.  I think we have covered much of the same bases and performed checks of the values for the various order types almost equivalently.  My PR however converts a lot of the order related strings to ENUMs and uses the ENUMs cast to do a good part of the validation.  

I notice yours does one additional step and does not include any None values in the data sent to the API, but I believe sending blanks for some of these fields is not a problem in the few cases where I can see that would occur.  I could add this to that branch if needed.

But do we really need this many additional helper functions when calling the core place/submit_order with the proper params would do the trick?  I think I would get lost in the naming convention and knowing what parameters each of these accepted that I'd avoid using them myself..

```
    def place_market_buy_order
    def place_limit_buy_order
    def place_stop_loss_buy_order
    def place_stop_limit_buy_order
    def place_market_sell_order
    def place_limit_sell_order
    def place_stop_loss_sell_order
    def place_stop_limit_sell_order
```

**Comment by ciresnave** [comment]
The helper functions were there to intentionally limit the parameters passed to submit_order to those applicable to each specific data type. You are 100% correct that you can do everything with just submit_order. That was the reason I put all of the parameters checks in submit_order rather than out in the helpers. I agree that using enums is probably better than what I did. I was planning on adding them to what I had. I originally wrote my code working backward from the spec so everything was strings. I haven't had a chance to look at your work but as long as it solves the same issues I couldn't care less if we use yours or mine. I'll take a look at yours (hopefully tomorrow) and we can work together on how best to proceed. I just had a baby so I fully understand that life gets in the way. Whether you or I push this API forward I think we (and any other core developers) need to find a way to establish a plan of action and a roadmap to where this API needs to be.

**Pull request merged**
